In [1]:
## Numpy

import numpy as np

In [3]:
# Пример создания массива:

# Создание одномерного массива
array_1d = np.array([1, 2, 3, 4, 5])

# Создание двумерного массива
array_2d = np.array([[1, 2, 3], [4, 5, 6]])

# Создание трехмерного массива
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print("Одномерный массив:\n", array_1d)
print("Двумерный массив:\n", array_2d)
print("Трехмерный массив:\n", array_3d)

# Создание массива с указанием типа данных
float_array = np.array([1, 2, 3], dtype=np.float32)

Одномерный массив:
 [1 2 3 4 5]
Двумерный массив:
 [[1 2 3]
 [4 5 6]]
Трехмерный массив:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


    Арифметические операции: сложение, вычитание, умножение, деление и возведение в степень.
    Линейная алгебра: операции с матрицами, такие как умножение, вычисление определителей и собственных значений.
    Статистика: функции для расчета среднего, медианы, стандартного отклонения и т.д.
    Преобразования Фурье: для анализа сигналов.

In [2]:
a = np.array([
    [[ 1,  2,  3],
     [ 4,  5,  6]],
    [[ 7,  8,  9],
     [10, 11, 12]]
])

slice_ = a[0, :, :]    # Все строки и столбцы из первого слоя
slice_2 = a[:, 1, :]   # Все слои, вторая строка, все столбцы
slice_3 = a[:, :, 0]   # Все слои, все строки, первый столбец

    # a[0, :, :] — двумерный массив, соответствующий первому слою.
    # a[:, 1, :] — двумерный массив, содержащий по одной строке (индекс 1) из каждого слоя.
    # a[:, :, 0] — двумерный массив, состоящий из первого столбца каждого слоя и строки.

subcube = a[:, ::-1, ::2]  # Все слои, строки в обратном порядке, каждый второй столбец