In [3]:
## Numpy

import numpy as np

# Пример создания массива:

# Создание одномерного массива
array_1d = np.array([1, 2, 3, 4, 5])

# Создание двумерного массива
array_2d = np.array([[1, 2, 3], [4, 5, 6]])

# Создание трехмерного массива
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print("Одномерный массив:\n", array_1d)
print("Двумерный массив:\n", array_2d)
print("Трехмерный массив:\n", array_3d)

# Создание массива с указанием типа данных
float_array = np.array([1, 2, 3], dtype=np.float32)

Одномерный массив:
 [1 2 3 4 5]
Двумерный массив:
 [[1 2 3]
 [4 5 6]]
Трехмерный массив:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


    Арифметические операции: сложение, вычитание, умножение, деление и возведение в степень.
    Линейная алгебра: операции с матрицами, такие как умножение, вычисление определителей и собственных значений.
    Статистика: функции для расчета среднего, медианы, стандартного отклонения и т.д.
    Преобразования Фурье: для анализа сигналов.